DROP TABLE IF EXISTS usuarios_servidores;
DROP TABLE IF EXISTS mensajes;
DROP TABLE IF EXISTS canales;
DROP TABLE IF EXISTS servidores;
DROP TABLE IF EXISTS usuarios;

DROP SCHEMA IF EXISTS michicode;